"""@Rule "|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-| INFO"
@Event eachPlayer
@Team 1
@Slot 0
"""

"""@Rule "|-| Total Rules Usage (With Conditions Or Actions): 114 |-|"
@Event eachPlayer
@Team 1
@Slot 0
"""

"""@Rule "|-| Total G.VARS Usage: A,B,C,D,E,F |-|"
@Event eachPlayer
@Team 1
@Slot 0
"""

"""@Rule "|-| Total P.VARS Usage: Ä„,B,C,D,E,F,G,H,I,J,K,L,M |-|"
@Event eachPlayer
@Team 1
@Slot 0
"""

"""@Rule "|-| Created By \"IRLININ\" |-|"
@Event eachPlayer
@Team 1
@Slot 0
"""
